<a href="https://colab.research.google.com/github/andreafloresk/Basa-de-datos/blob/main/actividad4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

adultpath = '/content/drive/My Drive/a4/adult.csv'
antropath = '/content/drive/My Drive/a4/antropometria-dataset-2.csv'

df1=pd.read_csv(adultpath)
df2=pd.read_csv(antropath)

df1.head(5)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,the label
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [ ]:
favs=["entidad","peso","sexo","desc_ent"]
ndf2=df2[favs]
ndf2

       entidad   peso  sexo                         desc_ent
0           21  73.70     2                           PUEBLA
1           10  35.65     2                          DURANGO
2            1  54.80     2                   AGUASCALIENTES
3            9  33.40     1                 DISTRITO FEDERAL
4           21  97.95     2                           PUEBLA
...        ...    ...   ...                              ...
18635       30  75.80     2  VERACRUZ DE IGNACIO DE LA LLAVE
18636        4  69.40     2                         CAMPECHE
18637       30  46.75     1  VERACRUZ DE IGNACIO DE LA LLAVE
18638       25  59.05     2                          SINALOA
18639        1  80.00     2                   AGUASCALIENTES

[18640 rows x 4 columns]

In [ ]:
pd.pivot_table(ndf2,index="desc_ent",aggfunc="mean", values="peso")

                                      peso
desc_ent
AGUASCALIENTES                   66.357786
BAJA CALIFORNIA                  68.467270
BAJA CALIFORNIA SUR              71.809198
CAMPECHE                         65.418475
CHIAPAS                          57.613775
CHIHUAHUA                        66.656005
COAHUILA DE ZARAGOZA             68.154142
COLIMA                           68.743648
DISTRITO FEDERAL                 65.119273
DURANGO                          66.354922
GUANAJUATO                       63.936390
GUERRERO                         60.466315
HIDALGO                          59.995917
JALISCO                          66.697270
MEXICO                           60.680850
MICHOACAN DE OCAMPO              64.900000
MORELOS                          63.541295
NAYARIT                          66.541827
NUEVO LEON                       67.239853
OAXACA                           58.800067
PUEBLA                           60.102996
QUERETARO                        63.547342
QUINTANA ROO                     64.238904
SAN LUIS POTOSI                  60.576912
SINALOA                          68.051272
SONORA                           68.849473
TABASCO                          66.554701
TAMAULIPAS                       68.210911
TLAXCALA                         62.085398
VERACRUZ DE IGNACIO DE LA LLAVE  62.546117
YUCATAN                          62.706315
ZACATECAS                        64.238524

In [ ]:
pd.pivot_table(ndf2,values="peso",aggfunc="mean", index="desc_ent",columns="sexo")

sexo                                     1          2
desc_ent
AGUASCALIENTES                   69.985381  63.254292
BAJA CALIFORNIA                  71.391818  65.893667
BAJA CALIFORNIA SUR              75.561015  68.168959
CAMPECHE                         68.622637  62.920493
CHIAPAS                          58.365222  57.096111
CHIHUAHUA                        68.892642  64.815295
COAHUILA DE ZARAGOZA             68.873094  67.467348
COLIMA                           70.998878  66.978393
DISTRITO FEDERAL                 69.460661  61.654128
DURANGO                          68.846451  64.400031
GUANAJUATO                       65.008000  63.100995
GUERRERO                         62.611437  58.899850
HIDALGO                          61.747958  58.972554
JALISCO                          67.076482  66.418111
MEXICO                           63.140314  58.887882
MICHOACAN DE OCAMPO              66.374612  63.784311
MORELOS                          65.741943  62.195391
NAYARIT                          68.822143  64.890564
NUEVO LEON                       70.168106  64.823014
OAXACA                           60.810332  57.450557
PUEBLA                           61.866875  58.820175
QUERETARO                        66.751233  60.860793
QUINTANA ROO                     65.149528  63.538000
SAN LUIS POTOSI                  62.614907  58.979163
SINALOA                          71.122911  65.565234
SONORA                           70.880406  67.024857
TABASCO                          69.255801  64.190187
TAMAULIPAS                       72.060601  64.866851
TLAXCALA                         64.784437  60.201164
VERACRUZ DE IGNACIO DE LA LLAVE  65.324094  60.565646
YUCATAN                          65.717541  60.537515
ZACATECAS                        66.096483  62.757788

In [ ]:
pivot_table = pd.pivot_table(df1, index='marital-status', aggfunc='size')
print(pivot_table)

marital-status
 Divorced                  4443
 Married-AF-spouse           23
 Married-civ-spouse       14976
 Married-spouse-absent      418
 Never-married            10683
 Separated                 1025
 Widowed                    993
 test_category_female         1
 test_category_male           2
dtype: int64

In [ ]:
pivot_table1 = df1.pivot_table(index='marital-status', columns='education', values='hours-per-week', aggfunc='mean')
print(pivot_table1)

education                    10th       11th       12th    1st-4th    5th-6th  \
marital-status
 Divorced               40.808333  40.023077  39.692308  32.800000  38.900000
 Married-AF-spouse            NaN        NaN        NaN        NaN        NaN
 Married-civ-spouse     41.664756  40.514124  42.561538  39.802469  40.209302
 Married-spouse-absent  41.866667  39.526316  42.625000  39.916667  35.750000
 Never-married          31.168975  28.047782  30.702586  39.307692  38.595506
 Separated              40.489796  38.416667  39.214286  38.888889  37.444444
 Widowed                32.512821  33.868421  39.900000  30.176471  31.071429
 test_category_female         NaN        NaN        NaN        NaN        NaN
 test_category_male           NaN        NaN        NaN        NaN        NaN

education                 7th-8th        9th   Assoc-acdm   Assoc-voc  \
marital-status
 Divorced               40.657534  37.281250    40.719212   41.085470
 Married-AF-spouse            NaN        NaN    21.500000   44.000000
 Married-civ-spouse     41.490251  40.765217    42.926087   42.923077
 Married-spouse-absent  37.071429  39.555556    36.000000   38.076923
 Never-married          37.991150  35.477419    37.670623   40.809392
 Separated              34.391304  38.181818    41.866667   38.928571
 Widowed                30.703125  29.478261    33.913043   33.439024
 test_category_female         NaN        NaN          NaN         NaN
 test_category_male           NaN        NaN          NaN         NaN

education                Bachelors   Doctorate    HS-grad    Masters  \
marital-status
 Divorced                43.053114   50.363636  40.668320  43.789700
 Married-AF-spouse       45.000000         NaN  43.000000        NaN
 Married-civ-spouse      44.165462   47.045455  42.635501  44.658026
 Married-spouse-absent   41.735294   46.714286  39.661157  47.000000
 Never-married           40.450696   47.616438  38.691162  42.433168
 Separated               42.500000   32.714286  38.189655  43.240000
 Widowed                 35.414634   35.857143  32.693237  36.878049
 test_category_female          NaN         NaN  40.000000        NaN
 test_category_male            NaN         NaN  40.000000        NaN

education                Preschool   Prof-school   Some-college
marital-status
 Divorced                72.000000     45.600000      40.898971
 Married-AF-spouse             NaN           NaN      40.000000
 Married-civ-spouse      40.950000     47.662621      43.493612
 Married-spouse-absent   40.000000     43.333333      37.013158
 Never-married           32.181818     48.741935      33.960109
 Separated               40.000000     42.875000      40.150000
 Widowed                 23.333333     33.200000      32.645349
 test_category_female          NaN           NaN            NaN
 test_category_male            NaN           NaN            NaN

In [42]:
favs1=["education","marital-status","hours-per-week","age","sex"]
ndf1=df1[favs1]
ndf1

        education         marital-status  hours-per-week  age      sex
0       Bachelors          Never-married              40   39     Male
1       Bachelors     Married-civ-spouse              13   50     Male
2         HS-grad               Divorced              40   38     Male
3            11th     Married-civ-spouse              40   53     Male
4       Bachelors     Married-civ-spouse              40   28   Female
...           ...                    ...             ...  ...      ...
32559     HS-grad          Never-married              20   22     Male
32560     HS-grad     Married-civ-spouse              40   52   Female
32561     HS-grad     test_category_male              40   52     Male
32562     HS-grad     test_category_male              40   52     Male
32563     HS-grad   test_category_female              40   52   Female

[32564 rows x 5 columns]

In [46]:
pd.pivot_table(ndf1, index=['marital-status', 'education'], columns='sex', values=['hours-per-week', 'age'], aggfunc="median")

                                         age       hours-per-week
sex                                   Female  Male         Female  Male
marital-status         education
 Divorced               10th            45.0  39.0           40.0  40.0
                        11th            41.0  38.0           40.0  40.0
                        12th            41.0  41.0           40.0  40.0
                        1st-4th         64.0  63.0           28.0  40.0
                        5th-6th         53.0  56.0           40.0  40.0
                        7th-8th         52.0  49.5           40.0  40.0
                        9th             46.0  46.0           40.0  40.0
                        Assoc-acdm      40.0  41.0           40.0  40.0
                        Assoc-voc       41.0  38.0           40.0  40.0
                        Bachelors       43.0  44.0           40.0  40.0
                        Doctorate       50.5  50.0           50.0  50.0
                        HS-grad         43.0  40.0           40.0  40.0
                        Masters         46.0  47.0           40.0  45.0
                        Preschool        NaN  36.0            NaN  72.0
                        Prof-school     42.0  44.5           40.0  50.0
                        Some-college    42.0  42.0           40.0  40.0
 Married-AF-spouse      Assoc-acdm      31.5   NaN           21.5   NaN
                        Assoc-voc        NaN  29.0            NaN  44.0
                        Bachelors       27.0  34.5           40.0  50.0
                        HS-grad         33.5  29.0           31.5  60.0
                        Some-college    28.0  26.0           40.0  40.0
 Married-civ-spouse     10th            32.0  48.0           40.0  40.0
                        11th            42.0  41.0           40.0  40.0
                        12th            34.0  41.5           40.0  40.0
                        1st-4th         44.5  51.0           30.0  40.0
                        5th-6th         43.0  46.0           40.0  40.0
                        7th-8th         46.0  52.0           40.0  40.0
                        9th             40.5  45.0           40.0  40.0
                        Assoc-acdm      36.0  40.0           40.0  40.0
                        Assoc-voc       35.0  40.0           40.0  40.0
                        Bachelors       37.0  42.0           40.0  42.0
                        Doctorate       41.5  49.0           38.5  45.0
                        HS-grad         39.0  42.0           40.0  40.0
                        Masters         43.0  45.0           40.0  44.0
                        Preschool       46.0  52.0           40.0  40.0
                        Prof-school     39.0  44.0           40.0  50.0
                        Some-college    38.0  42.0           40.0  40.0
 Married-spouse-absent  10th            39.0  49.0           40.0  40.0
                        11th            30.0  32.5           40.0  40.0
                        12th            25.5  46.0           45.0  42.5
                        1st-4th         33.0  41.0           40.0  40.0
                        5th-6th         50.0  41.0           34.0  40.0
                        7th-8th         44.0  49.5           37.5  40.0
                        9th             49.0  30.5           30.0  40.0
                        Assoc-acdm      42.5  44.5           35.5  32.5
                        Assoc-voc       36.5  46.0           40.0  40.0
                        Bachelors       42.0  40.5           40.0  40.0
                        Doctorate       43.0  42.5           40.0  60.0
                        HS-grad         38.0  40.0           40.0  40.0
                        Masters         49.0  49.0           40.0  50.0
                        Preschool        NaN  46.0            NaN  40.0
                        Prof-school     52.0  51.0           40.0  45.0
                        Some-college    31.0  37.0           40.0  40.0
 Never-married          10th            18.0  20.0           26.5  40.0
                        11th            18.0  18.0           22.0  30.0
                        12th            18.0  20.5           25.0  39.0
                        1st-4th         32.0  28.0           40.0  40.0
                        5th-6th         32.0  26.0           40.0  40.0
                        7th-8th         31.0  27.0           40.0  40.0
                        9th             26.5  23.0           38.0  40.0
                        Assoc-acdm      27.0  27.0           40.0  40.0
                        Assoc-voc       28.0  29.0           40.0  40.0
                        Bachelors       27.0  28.0           40.0  40.0
                        Doctorate       42.0  36.0           50.0  40.0
                        HS-grad         26.0  26.0           40.0  40.0
                        Masters         37.0  35.0           40.0  40.0
                        Preschool       36.5  27.5           30.0  36.0
                        Prof-school     32.0  34.0           50.0  50.0
                        Some-college    22.0  23.0           35.0  40.0
 Separated              10th            34.0  38.0           40.0  40.0
                        11th            35.5  34.5           40.0  40.0
                        12th            35.0  36.0           40.0  40.0
                        1st-4th         50.0  56.0           40.0  37.5
                        5th-6th         39.0  42.0           40.0  40.0
                        7th-8th         45.0  30.0           32.0  40.0
                        9th             45.0  41.5           40.0  40.0
                        Assoc-acdm      39.5  38.0           40.0  40.0
                        Assoc-voc       40.0  39.0           40.0  40.0
                        Bachelors       42.5  40.0           40.0  40.0
                        Doctorate       40.0  46.0           32.0  40.0
                        HS-grad         38.0  36.0           40.0  40.0
                        Masters         44.0  47.0           40.0  45.0
                        Preschool       48.0   NaN           40.0   NaN
                        Prof-school     44.0  43.0           40.0  48.0
                        Some-college    38.0  37.0           40.0  40.0
 Widowed                10th            60.0  57.0           35.0  40.0
                        11th            56.0  60.0           40.0  40.0
                        12th            56.0  65.0           40.0  44.0
                        1st-4th         63.0  69.5           30.0  42.5
                        5th-6th         65.0  82.0           40.0  15.0
                        7th-8th         64.0  68.0           35.0  30.0
                        9th             63.0  59.0           25.0  40.0
                        Assoc-acdm      54.0  36.5           40.0  40.0
                        Assoc-voc       62.0  66.5           40.0  50.0
                        Bachelors       55.0  64.0           40.0  40.0
                        Doctorate       63.5  64.0           40.0  40.0
                        HS-grad         60.5  62.5           37.0  40.0
                        Masters         56.0  66.5           40.0  40.0
                        Preschool       52.5  71.0           30.0  10.0
                        Prof-school     68.0  42.5           20.0  45.0
                        Some-college    58.0  60.5           40.0  40.0
 test_category_female   HS-grad         52.0   NaN           40.0   NaN
 test_category_male     HS-grad          NaN  52.0            NaN  40.0